spring:
  profiles:
    active: dev #开发环境
#    active: prod #生产环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M

server:
  port: 8095
  servlet:
#    context-path: /toolskit


mybatis:
  mapper-locations:
    - classpath:dao/*.xml

#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: toolskit-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: Bearer  #JWT负载中拿到开头

#redis:
#  database: codell
#  key:
#    admin: 'codell:admin'
#    resourceList: 'ums:resourceList'
#  expire:
#    common: 86400 # 24小时


logging:
  level:
    com.security.toolskit.mapper: debug
    root: info #日志配置DEBUG,INFO,WARN,ERROR
#  file: demo_log.log #配置日志生成路径
#  path: /var/logs #配置日志文件名称

